live_config_reload = true

import = [
  "~/.config/alacritty/tokyonight_night.toml"
]

[window]
title = "Terminal"
dynamic_title = false
opacity = 0.95

[selection]
save_to_clipboard = true

[scrolling]
history = 10000

[bell]
duration = 0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
mouse.enabled = true

[font]
size = 11.5
builtin_box_drawing = true
normal.family = "SauceCodeProNFM"
normal.style  = "Regular"

